DROP DATABASE IF EXISTS employee_DB;
CREATE DATABASE employee_DB;

USE employee_DB;

CREATE TABLE department(
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,  
  PRIMARY KEY (ID)
);

CREATE TABLE role(
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(30) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES department(ID)
);

CREATE TABLE employee(
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    ROLE_ID INT NOT NULL,
    MANAGER_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES role(ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES employee(ID)
);
